# NumPy Array Attributes

# Generating random numbers

One dimensional array

In [23]:
import numpy as np
rng = np.random.default_rng(seed = 1701)
n1 = rng.integers(10, size = 10)
print(n1)

[9 4 0 3 8 6 3 1 3 7]


Two dimensional array

In [3]:
n2 = rng.integers(10 , size = (5 , 7))
print(n2)

[[4 0 2 3 0 0 6]
 [9 4 3 5 5 0 8]
 [3 5 2 2 1 8 8]
 [5 3 0 0 8 5 8]
 [5 1 6 2 3 1 2]]


Three dimensional array

In [4]:
n3 = rng.integers(10 , size = (4 , 4 , 5))
print(n3)

[[[5 6 2 5 2]
  [7 9 3 5 6]
  [0 2 0 2 9]
  [4 3 9 9 2]]

 [[2 4 0 0 3]
  [0 0 2 3 2]
  [7 4 7 9 3]
  [6 6 5 0 2]]

 [[5 6 4 8 2]
  [5 6 2 7 3]
  [8 9 2 7 2]
  [5 3 6 8 2]]

 [[0 6 5 8 4]
  [3 2 4 3 9]
  [2 3 6 1 3]
  [0 0 1 9 5]]]


Sum of all the random numbers

In [5]:
rng = np.random.default_rng()
N = rng.random(200)
np.sum(N)

94.47222951882542

In [6]:
sum(N)

94.47222951882543

# Array Indexing

In [7]:
n1

array([9, 4, 0, 3, 8, 6, 3, 1, 3, 7])

In [8]:
n1[0]

9

In [9]:
n1[5]

6

In [10]:
n2[4 , 5]

1

In [11]:
n2[3 , -1]

8

# Subarrays

first four elements

In [12]:
n1[:4]

array([9, 4, 0, 3])

Elements after index six

In [13]:
n1[6:]

array([3, 1, 3, 7])

all elements reversed

In [14]:
n1[::-1]

array([7, 3, 1, 3, 6, 8, 3, 0, 4, 9])

# Multidimensional Subarrays

it will show first two rows and three columns

In [15]:
n2[:2, :3]

array([[4, 0, 2],
       [9, 4, 3]])

it will reverse all rows and columns

In [16]:
n2[::-1, ::-1]

array([[2, 1, 3, 2, 6, 1, 5],
       [8, 5, 8, 0, 0, 3, 5],
       [8, 8, 1, 2, 2, 5, 3],
       [8, 0, 5, 5, 3, 4, 9],
       [6, 0, 0, 3, 2, 0, 4]])

# Creating copies of arrays

In [18]:
n2_sub_copy = n2[:3, :1].copy()
print(n2_sub_copy)

[[4]
 [9]
 [3]]


# Reshaping of arrays

In [22]:
r1 = np.arange(1, 10).reshape(3, 3)
print(r1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Minimum and Maximum

In [24]:
array1 = rng.random(100000)
sum(array1)

49898.04654554252

In [25]:
min(array1)

4.528128529357467e-06

In [26]:
max(array1)

0.9999936155641657

# Multidimensional Aggregates

In [27]:
M = rng.integers(0 , 10 , (4 , 6))
print(M)

[[7 9 3 5 7 9]
 [6 4 5 2 0 2]
 [5 6 0 8 7 3]
 [0 7 3 3 5 2]]


In [28]:
M.sum() #Sum all the integers

108

In [29]:
M.min(axis=0)

array([0, 4, 0, 2, 0, 2])

In [30]:
M.max(axis=0)

array([7, 9, 5, 8, 7, 9])

# Broadcasting

In [31]:
a = np.array([0, 1, 4])
b = np.array([2, 4, 5])
a + b

array([2, 5, 9])

In [32]:
a + 5     #add 5 in each element of the array

array([5, 6, 9])

Write the arrays in different axis

In [33]:
a = np.arange(5)
b = np.arange(5)[:, np.newaxis]
print(a)
print(b)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


adding two dimensional array to one dimensional array

In [42]:
T = np.ones((2, 3))
print(T)

[[1. 1. 1.]
 [1. 1. 1.]]


In [43]:
p = np.arange(3)
print(p)

[0 1 2]


In [44]:
T + p

array([[1., 2., 3.],
       [1., 2., 3.]])

#Example 2

In [40]:
z = np.arange(3).reshape((3, 1))
print(z)

[[0]
 [1]
 [2]]


In [41]:
y = np.arange(3)
print(y)

[0 1 2]


In [39]:
z + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Centering an Array

In [46]:
n1mean = n1.mean(0)
print(n1mean)

4.4


In [47]:
n1_centered = n1 - n1mean
print(n1_centered)

[ 4.6 -0.4 -4.4 -1.4  3.6  1.6 -1.4 -3.4 -1.4  2.6]


In [48]:
n1_centered.mean(0)

-3.552713678800501e-16